/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.toko;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class penjualan extends javax.swing.JInternalFrame {

    /**
     * Creates new form penjualan
     */
    model.mbarang modelbarang;
    model.mpenjualan modelpenjualan;
    ArrayList<String> daftarkode = new ArrayList<String>();

    public penjualan() {
        try {
            initComponents();
            kd_barang.requestFocus();
            modelbarang = new model.mbarang();
            refrestable();

        } catch (SQLException ex) {
            Logger.getLogger(penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kd_barang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        kd_barang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kd_barangKeyPressed(evt);
            }
        });

        jLabel1.setText("kode barang");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "kd_barang", "nama", "harga", "quantity", "total"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setText("simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kd_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kd_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kd_barangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kd_barangKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (modelbarang.cekbarang(kd_barang.getText())) {
                if (!daftarkode.contains(kd_barang.getText())) {
                    try {
                        // TODO add your handling code here:
                        String[] data = modelbarang.getdatawithid(kd_barang.getText());
                        String data1 = data[0];
                        String data2 = data[1];
                        String data3 = data[2];
                        String data4 = "1";
                        double hitung = Integer.parseInt(data3) * Integer.parseInt(data4);
                        String data5 = "" + hitung;
                        Object[] row = {data1, data2, data3, data4, data5};
                        DefaultTableModel model = (DefaultTableModel) table.getModel();
                        model.addRow(row);
                        //tambah kodebarang ke array list
                        daftarkode.add(data1);
                    } catch (SQLException ex) {
                        Logger.getLogger(penjualan.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    message("data duplikat");
                }
            } else {
                message("data tidak di temukan");
            }

            kd_barang.setText("");
        }

    }//GEN-LAST:event_kd_barangKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            simpan();
        } catch (SQLException ex) {
            Logger.getLogger(penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void refrestable() {
    }

    private void simpan() throws SQLException {
        int jumlah_baris = table.getRowCount();
        
        if (jumlah_baris == 0) {
            JOptionPane.showMessageDialog(rootPane, "Table Masih Kosong!");
        } else {
            System.out.println("jumlah baris"+jumlah_baris);
            
                int i = 0;
                String[] data = new String[6];
                data[0] = modelpenjualan.getnotransaksi();
                while (i < jumlah_baris) {
                    data[1] = "";
                    data[2] = (String) table.getValueAt(i, 0);//kodebarang
                    data[3] = (String) table.getValueAt(i, 2);//harga
                    data[4] = (String) table.getValueAt(i, 3);//quantity
                    data[5] = (String) table.getValueAt(i, 5);//total
                    modelpenjualan.tambahbarang(data);
                    for (int j = 0; j < data.length; j++) {
                        System.out.println("data ke " + i + " = " + data[j]);
                    }
                    i++;
                }
                JOptionPane.showMessageDialog(rootPane, "Berhasil Menyimpan!");
            
        }
    }

    public void message(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kd_barang;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
