/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.toko;

import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class rekap_penjualan extends javax.swing.JInternalFrame {

    /**
     * Creates new form tambahdatapenjualan
     */
    model.mbarang modelbarang;
    model.mpenjualan modelpenjualan;

    public rekap_penjualan() throws SQLException {
        initComponents();
        modelbarang = new model.mbarang();
        modelpenjualan = new model.mpenjualan();

    }
public void lebarkolom(){
table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tglawal = new com.toedter.calendar.JDateChooser();
        tglakhir = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No_transaksi", "tgl transaksi", "nama barang", "harga", "jml", "total harga"
            }
        ));
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(100);
            table.getColumnModel().getColumn(1).setPreferredWidth(150);
            table.getColumnModel().getColumn(2).setPreferredWidth(150);
            table.getColumnModel().getColumn(3).setPreferredWidth(150);
            table.getColumnModel().getColumn(4).setPreferredWidth(35);
            table.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 460));
        getContentPane().add(tglawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 120, 40));
        getContentPane().add(tglakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 120, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("tanggal awal");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("tanggal akhir");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tgl1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tgl2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print1.png"))); // NOI18N
        simpan.setBorderPainted(false);
        simpan.setContentAreaFilled(false);
        simpan.setEnabled(false);
        simpan.setFocusPainted(false);
        simpan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print2.png"))); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Date pertama = this.tglawal.getDate();
            Date kedua = this.tglakhir.getDate();
            String tglawal = gettanggal(pertama);
            String tglakhir = gettanggal(kedua);
            if (pertama.equals(kedua)) {
                JTable gettabel = new JTable();
                gettabel.setModel(modelpenjualan.getdatapenjualantgl(tglawal, tglakhir));
                for (int i = 0; i < gettabel.getRowCount(); i++) {
                    double harga = Double.parseDouble(gettabel.getValueAt(i, 3).toString());
                    double total = Double.parseDouble(gettabel.getValueAt(i, 5).toString());
                    String uangharga = rubahuangkerupiah(harga);
                    String uangtotal = rubahuangkerupiah(total);
                    gettabel.setValueAt(uangharga, i, 3);
                    gettabel.setValueAt(uangtotal, i, 5);
                }
                table.setModel(gettabel.getModel());
                simpan.setEnabled(true);
            } else if (pertama.before(kedua)) {
                JTable gettabel = new JTable();
                gettabel.setModel(modelpenjualan.getdatapenjualantgl(tglawal, tglakhir));
                for (int i = 0; i < gettabel.getRowCount(); i++) {
                    double harga = Double.parseDouble(gettabel.getValueAt(i, 3).toString());
                    double total = Double.parseDouble(gettabel.getValueAt(i, 5).toString());
                    String nama = gettabel.getValueAt(i, 2).toString().toUpperCase();
                    String uangharga = rubahuangkerupiah(harga);
                    String uangtotal = rubahuangkerupiah(total);
                    gettabel.setValueAt(nama, i, 2);
                    gettabel.setValueAt(uangharga, i, 3);
                    gettabel.setValueAt(uangtotal, i, 5);
                }
                table.setModel(gettabel.getModel());
                simpan.setEnabled(true);
            } else {
                message("tgl awal harus tidak boleh melebihi tgl akhir");
            }
        } catch (SQLException ex) {
            Logger.getLogger(rekap_penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try {
            MessageFormat header = new MessageFormat("rekap penjualan tgl"+gettanggal(tglawal.getDate())+" - "+gettanggal(tglakhir.getDate()));
            MessageFormat footer = new MessageFormat("page(1,number,integer)");
            table.print(JTable.PrintMode.FIT_WIDTH,header,footer);
        } catch (PrinterException ex) {
            Logger.getLogger(rekap_penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_simpanActionPerformed

    public String gettanggal(Date date) {
        DateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        return dateformat.format(date);
    }
public String rubahuangkerupiah(double uang) {
        String mataUang = String.format("Rp.%,.0f", uang).replaceAll(",", ".") + ",00";
        return mataUang;
    }
    public void message(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton simpan;
    private javax.swing.JTable table;
    private com.toedter.calendar.JDateChooser tglakhir;
    private com.toedter.calendar.JDateChooser tglawal;
    // End of variables declaration//GEN-END:variables
}
