/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.toko;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class tambahbarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form tambahbarang
     */
    model.mbarang modelbarang;
String tombol = "simpan";
    public tambahbarang() throws SQLException {
        initComponents();
        modelbarang = new model.mbarang();
        refrestable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kd_barang = new javax.swing.JTextField();
        nama_barang = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        keterangan = new javax.swing.JTextArea();
        simpan = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("kode barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("nama barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("stok");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("keterangan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        kd_barang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(kd_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 230, 30));

        nama_barang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(nama_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 230, 30));

        stok.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 230, 30));

        harga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 230, 30));

        keterangan.setColumns(20);
        keterangan.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        keterangan.setRows(5);
        jScrollPane1.setViewportView(keterangan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 230, 100));

        simpan.setForeground(new java.awt.Color(255, 255, 255));
        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sav1.png"))); // NOI18N
        simpan.setMnemonic('s');
        simpan.setBorderPainted(false);
        simpan.setContentAreaFilled(false);
        simpan.setFocusPainted(false);
        simpan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sav2.png"))); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del1.png"))); // NOI18N
        reset.setMnemonic('h');
        reset.setBorderPainted(false);
        reset.setContentAreaFilled(false);
        reset.setFocusPainted(false);
        reset.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del2.png"))); // NOI18N
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 640, 370));

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 360, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cari1.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        if (table.getSelectedRow() == -1) {
            bersih();
            tombol = "simpan";
        } else {
            String kdbarang = table.getValueAt(table.getSelectedRow(), 0).toString();
            modelbarang.hapusbarang(kdbarang);
            bersih();
            refrestable();
        }
    }//GEN-LAST:event_resetActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        if (tombol.equalsIgnoreCase("simpan")) {
            if (modelbarang.tambahbarang(getdata())) {
                bersih();
            } else {
                message("gagal input data, cek kembali inputan");
            }
        } else {
            if (modelbarang.updatebarang(getdata())) {
                message("data berhasil di ubah");
                bersih();
            } else {
                message("data gagal di ubah");
            }
            tombol = "simpan";
            simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sav1.png")));
            simpan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sav2.png")));
        }
        refrestable();
    }//GEN-LAST:event_simpanActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        try {
            table.setModel(modelbarang.getdatasearch(search.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(tambahbarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchKeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int selectindex = table.getSelectedRow();

        kd_barang.setText(model.getValueAt(selectindex, 0).toString());
        nama_barang.setText(model.getValueAt(selectindex, 1).toString());
        harga.setText(model.getValueAt(selectindex, 2).toString());
        stok.setText(model.getValueAt(selectindex, 3).toString());
        keterangan.setText(model.getValueAt(selectindex, 4).toString());

        tombol = "update";
        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/up1.png")));
        simpan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/up2.png")));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked
    public void bersih() {
        kd_barang.setText("");
        nama_barang.setText("");
        harga.setText("");
        stok.setText("");
        keterangan.setText("");
    }

    public String[] getdata() {
        String[] data = new String[5];
        data[0] = kd_barang.getText();
        data[1] = nama_barang.getText();
        data[2] = harga.getText();
        data[3] = stok.getText();
        data[4] = keterangan.getText();
        return data;
    }

    public void refrestable() {
        try {
            table.setModel(modelbarang.getdata());
        } catch (SQLException ex) {
            Logger.getLogger(tambahbarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void message(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kd_barang;
    private javax.swing.JTextArea keterangan;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JButton reset;
    private javax.swing.JTextField search;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField stok;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
